### ISSUE TITLE
[jme3-alloc-examples] Consider adding a demo app  

### ISSUE THREAD

**Issue by Ali-RS** [Software-Hardware-Codesign/jme-alloc#16]
Please add a separate example app demonstrating multithreading and [direct memory releasing](https://github.com/jMonkeyEngine/jmonkeyengine/blob/d76d4dc8c67bc99c5fd197d41a102639194a4e3b/jme3-examples/src/main/java/jme3test/app/TestReleaseDirectMemory.java#L43) in JME context.

**Comment by Scrappers-glitch** [comment]
### This a list of tech-demos that could be made on a separate module `jme3-testalloc`: 
- [ ] `HelloJme3alloc.java`: demonstrating the basic alllocation/deallocation capabilities. 
- [ ] `HelloThreadedJme3alloc.java`: testing the multi-threading capabilities.
- [ ] `HelloMemoryCopy.java`: demonstrating `memoryCopy(ByteBuffer to, ByteBuffer from, long size)`.
- [ ] `HelloMemorySet.java`: demonstrating `memorySet(ByteBuffer buffer, int value, long size)`.
- [ ] `HelloMemoryMove.java`: demonstrating `memoryMove(ByteBuffer to, ByteBuffer from, long size)`.
- [ ] `HelloJme3allocLog.java` (WIP).

**Comment by pavly-gerges** [comment]
@Ali-RS I will notify you on forums, if you want to add more techdemos later after fixing issue #25, because i want to examine the windows github-runner image output.
