### ISSUE TITLE
[Core-Bug] The NativeBinaryLoader is using a system specific file separator 

### ISSUE THREAD

**Issue by pavly-gerges** [Software-Hardware-Codesign/jme-alloc#25]
The [NativeBinaryLoader-Utility](https://github.com/Software-Hardware-Codesign/jme-alloc/blob/dbda01f4c541ad103a6cb015919b8e7e7b5edd05/jme3-alloc/src/main/java/com/jme3/alloc/util/loader/NativeDynamicLibrary.java#L40) is using the Unix specific file separator forward slash '/' which is not working on windows raising a [`java.lang.StackOverflowError`](https://github.com/Software-Hardware-Codesign/jme-alloc/actions/runs/4070923389/jobs/7012308426#step:5:29) because of the several failed retry clean-extract criteria with failed attempts on each trial.

**Comment by Ali-RS** [comment]
Note, I think it should be fine as far as you construct the path string from a java Path or File.

I guess this is the problematic code:
https://github.com/Software-Hardware-Codesign/jme-alloc/blob/dbda01f4c541ad103a6cb015919b8e7e7b5edd05/jme3-alloc/src/main/java/com/jme3/alloc/util/loader/NativeBinaryLoader.java#L120-L122

Try something like 
```
return Paths.get(System.getProperty("user.dir"), library.getLibrary()).toAbsolutePath().toString();
```

Edit:

The same for 
https://github.com/Software-Hardware-Codesign/jme-alloc/blob/dbda01f4c541ad103a6cb015919b8e7e7b5edd05/jme3-alloc/src/main/java/com/jme3/alloc/util/loader/NativeBinaryLoader.java#L185

and 

https://github.com/Software-Hardware-Codesign/jme-alloc/blob/dbda01f4c541ad103a6cb015919b8e7e7b5edd05/jme3-alloc/src/main/java/com/jme3/alloc/util/loader/NativeDynamicLibrary.java#L66

**Comment by pavly-gerges** [comment]
I am simply willing to use the [`System.getProperty("file.separator");`](https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/lang/System.html#getProperties()) to get the system specific file separator instead of the Unix forward slash '/'.

**Comment by Ali-RS** [comment]
>use the [System.getProperty("file.separator");](https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/lang/System.html#getProperties())

You can also use `File.separator`
