### ISSUE TITLE
[Question] Where is guava library used?

### ISSUE THREAD

**Issue by Ali-RS** [Software-Hardware-Codesign/jme-alloc#52]
Hi,

Curious to know where google guava library is used? And if it was necessary? 
Because its size is relatively large ( 2.9 MB).

https://github.com/Software-Hardware-Codesign/jme-alloc/blob/78067432ebea30ac23b711e0a417d9ede571d777/jme3-alloc/build.gradle#L75

**Comment by pavly-gerges** [comment]
The 'Gradle 'init' task' produces it by default, my suspicion is that it's used by the JUnit test API, however, the output jar doesn't include any of google guava libraries, I think that may be the `jre` is different from the guava-core, but idk, I have never used google-guava library.

**Comment by Ali-RS** [comment]
If it is only used by tests then you should change it to `testImplementation` or something, else it will be fetched by gradle for any app that uses jme3-alloc. 

>I think that may be the jre is different from the guava-core

`31.1-jre` is for desktop apps, there is also `31.1-android` version for android.

**Comment by pavly-gerges** [comment]
Thanks, I will look into this as soon before releasing the `1.0.0-beta`.
