### ISSUE TITLE
[API-Logging] Replace `stdout` print statements with jul or slf4j logging API

### ISSUE THREAD

**Issue by Ali-RS** [Software-Hardware-Codesign/jme-alloc#53]
for example, one place that uses `stdout` print statements is:

https://github.com/Software-Hardware-Codesign/jme-alloc/blob/89f0795110782e3d30b53c05d5918c50d6976332/jme3-alloc/src/main/java/com/jme3/alloc/util/NativeBufferUtils.java#L128

My recommendation would be to use slf4j with the log4j2 bridge.

**Comment by pavly-gerges** [comment]
Do you recommend log4j over the java logging API? 
I was going to use the stock java logging API.
I haven't used sl4j and/or log4j before, may be I could give them a try, but will not be on the `1.0.0-stable` release.

**Comment by Ali-RS** [comment]
>Do you recommend log4j over the java logging API?

Just my preference ;)

>I was going to use the stock java logging API.

Sure, you can use java logging API (JUL), JME also uses it so might better to follow the same.

**Comment by pavly-gerges** [comment]
@Ali-RS Feel free to review PR #60, I moved the autoLoading method to the NativeBinaryLoader, so everything is now in the relevant place and logging is restricted only to the NativeBinaryLoader utility.
